# Generated by Django 4.2.7 on 2024-02-22 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0002_alter_lessonwatched_is_used_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="users",
        ),
        migrations.AddField(
            model_name="userlesson",
            name="last_watched_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userlesson",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_lessons", to="course.lesson"
            ),
        ),
        migrations.AlterField(
            model_name="userlesson",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_lessons", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
