# Generated by Django 4.2.7 on 2024-02-22 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0003_remove_lesson_users_userlesson_last_watched_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="users",
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_courses", to="course.course"
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
