# Generated by Django 4.2.7 on 2024-02-22 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_remove_course_users_alter_usercourse_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonwatched",
            name="watch_time",
        ),
    ]
